name: Publish to npm (Conditional Tags)

on:
  push:
    tags:
      - "v*" # Matches tags like v1.0.0, v1.0.0-alpha.1, etc.

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      # Extract version from Git tag and update package.json
      - name: Sync version from tag
        run: |
          TAG_VERSION=$(echo "${GITHUB_REF#refs/tags/}" | sed 's/^v//')
          echo "Updating version in package.json to $TAG_VERSION"
          jq ".version=\"$TAG_VERSION\"" package.json > package.tmp.json
          mv package.tmp.json package.json
          echo "Package version set to $TAG_VERSION"
          cat package.json # Debugging: Print updated package.json

      # Install dependencies
      - name: Install dependencies
        run: |
          corepack enable
          bun install

      # Build the project
      - name: Build project
        run: bun run build

      # Determine npm publish tag
      - name: Determine publish tag
        id: tag
        run: |
          TAG="latest"
          if [[ "${GITHUB_REF#refs/tags/}" == *"-alpha"* ]]; then
            TAG="alpha"
          elif [[ "${GITHUB_REF#refs/tags/}" == *"-beta"* ]]; then
            TAG="beta"
          fi
          echo "Publish tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_ENV

      # Publish to npm
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --tag ${{ env.tag }}
